name: Test Package Deployment

on:
  workflow_dispatch
defaults:
  run:
    working-directory: ./
permissions:
  packages: write
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install
      run: npm i
    - name: Test
      run: npm test
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm i
      - name: Prepublish
        run: npm run build
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  notify_slack_success:
    runs-on: ubuntu-latest
    needs: [test, publish]
    if: success()
    steps:
      - name: Notify build success
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: integration_tests
          SLACK_COLOR: good
          SLACK_USERNAME: Github Actions CI/CD
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  notify_slack_failure:
    runs-on: ubuntu-latest
    needs: [test, publish]
    if: failure()
    steps:
      - name: Notify build failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: integration_tests
          SLACK_COLOR: '#FF0000'
          SLACK_USERNAME: Github Actions CI/CD
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}